### ISSUE TITLE
why do you use envoy

### ISSUE THREAD

**Issue by fizz12344321** [itsfergydanny/MomentoPerIslandEnvoys#1]
Hi, i am reading your project and i love it, can i ask u a question, why do you use Envoy in your project. Can you tell me the purpose, the pros and cons of this. thank u so much

**Comment by itsfergydanny** [comment]
> Hi, i am reading your project and i love it, can i ask u a question, why do you use Envoy in your project. Can you tell me the purpose, the pros and cons of this. thank u so much

What do you mean why do I use envoy? I don't understand your question
